<?php

/**
 * @file
 * Contains pw_page_title.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pw_page_title_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pw_page_title module.
    case 'help.page.pw_page_title':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Simple header contains background title and subtitle') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pw_page_title_theme() {
  return [
    'field__paragraph__field_pw_title__pw_page_title' => [
      'base hook' => 'field',
    ],
    'field__paragraph__field_pw_subtitle__pw_page_title' => [
      'base hook' => 'field',
    ],
    'field__paragraph__field_pw_image__pw_page_title' => [
      'base hook' => 'field',
    ],
    'paragraph__pw_page_title' => [
      'base hook' => 'paragraph',
    ],
  ];
}
